# Generated by Django 2.0.1 on 2018-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bylaws', models.FileField(upload_to='')),
                ('policies', models.FileField(upload_to='')),
            ],
        ),
    ]
