# Generated by Django 2.0.1 on 2018-05-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bylaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bylaws', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_shown', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.CharField(max_length=200)),
                ('fnc', models.CharField(max_length=200)),
                ('snc', models.CharField(max_length=200)),
                ('mw', models.CharField(max_length=200)),
                ('rep', models.CharField(max_length=200)),
                ('pub', models.CharField(max_length=200)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Projectionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(to='info.Movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AddField(
            model_name='officers',
            name='projectionists',
            field=models.ManyToManyField(to='info.Projectionist'),
        ),
    ]
