# Generated by Django 2.0.1 on 2018-05-26 15:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180525_1630'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('movies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='last_shown',
            new_name='showing_date',
        ),
    ]
