# Generated by Django 2.0.1 on 2018-05-26 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180526_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='A moving picture, for sure', max_length=10000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='showing_date',
            field=models.DateField(default=datetime.date(2018, 5, 26)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Superbad', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_src',
            field=models.CharField(default='https://www.youtube.com/embed/jPEYpryMp2s', max_length=1000),
        ),
    ]
