# Generated by Django 2.0.1 on 2018-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20180526_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='home/static/home/images/logo.png', upload_to='home/static/home/posters'),
        ),
    ]
