# Generated by Django 2.0.1 on 2018-05-27 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180526_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='officers',
            name='year',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='home/static/home/images/logo.png', upload_to='posters/%Y'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='showing_date',
            field=models.DateField(default=datetime.date(2018, 5, 27)),
        ),
    ]
